export enum ItemCategory {
  TOOLS = 'Tools',
  LIGHT_SOURCES = 'Light Source',
  PROTOTYPERS = 'Prototypers and Stations',
  REFINED_MATERIALS = 'Refined Material',
  WEAPONS = 'Weapons',
  ARMOUR = 'Armour',
  CLOTING = 'Cloting',
  HEALING = 'Healing',
  SHADOW_AND_MAGIC = 'Shadow and Magic',
  DECORATIONS = 'Decorations',
  ESTRUCTURES = 'Structures',
  STORAGE = 'Storage Solutions',
  COOKING = 'Cooking',
  FOOD_AND_GARDENING = 'Food and gardening',
  FISHING = 'Fishing',
  SEAFARING = 'Seafaring',
  BEEFALO_RIDING = 'Beefalo riding',
  TRINKET = 'Trinket',
}
